#!/usr/bin/env python3
# -*- coding: utf-8 -*-

   #########################################################################
 ##                                                                       ##
##           ┏━╸┏━┓╻ ╻┏━╸┏━┓   ╺┳╸╻ ╻╻ ╻┏┳┓┏┓ ┏┓╻┏━┓╻╻  ┏━╸┏━┓            ##
##           ┃  ┃ ┃┃┏┛┣╸ ┣┳┛    ┃ ┣━┫┃ ┃┃┃┃┣┻┓┃┗┫┣━┫┃┃  ┣╸ ┣┳┛            ##
##           ┗━╸┗━┛┗┛ ┗━╸╹┗╸    ╹ ╹ ╹┗━┛╹ ╹┗━┛╹ ╹╹ ╹╹┗━╸┗━╸╹┗╸            ##
##                         — www.flogisoft.com —                          ##
##                                                                        ##
############################################################################
##                                                                        ##
## Cover thumbnailer                                                      ##
##                                                                        ##
## Copyright (C) 2009 - 2024  Fabien Loison <http://www.flozz.fr/>        ##
##                                                                        ##
## This program is free software: you can redistribute it and/or modify   ##
## it under the terms of the GNU General Public License as published by   ##
## the Free Software Foundation, either version 3 of the License, or      ##
## (at your option) any later version.                                    ##
##                                                                        ##
## This program is distributed in the hope that it will be useful,        ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of         ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          ##
## GNU General Public License for more details.                           ##
##                                                                        ##
## You should have received a copy of the GNU General Public License      ##
## along with this program.  If not, see <http://www.gnu.org/licenses/>.  ##
##                                                                        ##
############################################################################
##                                                                        ##
## WEB SITE : https://github.com/flozz/cover-thumbnailer                  ##
##                                                                       ##
#########################################################################


"""Generates thumbnails for nautilus' folders.

Cover thumbnailer generates thumbnail that will be displayed instead of the
default folder icons. It has a specific presentation for music and pictures
folders, and a generic one for other folders.

Usage:
    cover-thumbnailer <directory's path> <output thumbnail's path>
"""

__version__ = "0.10.2"
__author__ = "Fabien Loison <http://www.flozz.fr/>"
__copyright__ = "Copyright © 2009 - 2024 Fabien LOISON"


import re
import sys
import os.path
from gi.repository import Gio

try:
    from PIL import Image
except:
    import Image


#==================================================================== CONF ====
#Base path for cover thumbnailer's pictures
if "DEVEL" in os.environ:
    BASE_PATH = "./share/" #For devel
else:
    BASE_PATH = os.path.expanduser("~/.local/share/arthum")

PICTURES_EXT = [
    ".jpg",  ".JPG", 
    ".jpeg", ".JPEG",
    ".png",  ".PNG", #Not interlaced
    ".gif",  ".GIF",
    ".bmp",  ".BMP", #Window ans OS/2 bitmap
    ".ico",  ".ICO", #Windows icon format
    ".tga",  ".TGA", #Truevision Targa format
    ".tif",  ".TIF", 
    ".tiff", ".TIFF", #Adobe Tagged Image File Format
    ".psd",  ".PSD", #Adobe Photosop format (only version 2.5 and 3.0)
]

MUSIC_EXT = [
    ".mp3", ".flac",
    ".m4a"
]

MUSIC_FG = os.path.join(BASE_PATH, "music_fg.png")
MUSIC_BG = os.path.join(BASE_PATH, "music_bg.png")

PICTURES_FG = os.path.join(BASE_PATH, "pictures_fg.png")
PICTURES_BG = os.path.join(BASE_PATH, "pictures_bg.png")

#==============================================================================

class Thumb(object):
    """
    Generate thumbnails for all kind of folders
    """
    def __init__(self, img_paths: list[str]):
        """
        Argument:
          * img_paths -- a list of picture path
        """
        self.img = []
        for path in img_paths:
            try:
                img = Image.open(path).convert("RGBA")
            except IOError:
                print("E: [%s:Thumb.__init__] Can't open '%s'." % (__file__, path))
            else:
                self.img.append(img)
        self.thumb = None

    def thumbnailize(self, image, twidth=128, theight=128, crop=True):
        """ Make thumbnail.

        Crop the picture if necessaries and return a thumbnail of it.

        Keyword argument:
          * twidth -- the width of the thumbnail (in pixels).
          * theight -- the width of the thumbnail (in pixels).
            NOTE: useless if crop = True
          * crop -- the resize method (True for having a squared thumbnail)

        NOTE: the size shouldn't be greater than 128 px for a standard
              freedesktop thumbnail.
        """
        width = image.size[0]
        height = image.size[1]
        if crop and width >= twidth and height >= theight:
            if width > height:
                left = int((width - height) / 2)
                upper = 0
                right = height + left
                lower = height
            else:
                left = 0
                upper = int((height - width) / 2)
                right = width
                lower = width + upper
            image = image.crop((left, upper, right, lower))
        image.thumbnail((twidth, theight), Image.LANCZOS)
        return image

    def music_thumbnail(self, bg_picture, fg_picture, crop=True):
        """ Makes thumbnails for music folders.

        Argument:
          * bg_picture -- the background picture
          * fg_picture -- the foreground picture
          * crop -- the resize method (True for having a squared thumbnail)
        """
        #Background picture
        bg = Image.open(bg_picture).convert("RGB")
        bg_width = bg.size[0]
        bg_height = bg.size[1]
        #Album cover
        cover = self.thumbnailize(self.img[0], bg_height, crop=crop)
        cover_width = cover.size[0]
        cover_height = cover.size[1]
        #Cover position on background
        delta = bg_width - bg_height #The left border of album
        x = int((bg_width - cover_width + delta) / 2)
        y = int((bg_height - cover_height) / 2)
        #Past cover on background
        bg.paste(cover, (x, y), cover)
        #Forground picture
        fg = Image.open(fg_picture).convert("RGBA")
        #Past forground on background+cover
        bg.paste(fg, (0, 0), fg)
        self.thumb = bg

    def music_thumbnail_mosaic(self, bg_picture, fg_picture, crop=True):
        """ Makes thumbnails composed by more than one cover for music folders.

        Argument:
          * bg_picture -- the background picture
          * fg_picture -- the foreground picture
          * crop -- the resize method (True for having a squared thumbnail)

        NOTE: call this function ONLY if self.img has, at least, two pictures.
        """
        #Background picture
        bg = Image.open(bg_picture).convert("RGB")
        bg_width = bg.size[0]
        bg_height = bg.size[1]
        #Album covers
        covers_thumb = []
        for img in self.img:
            cover_thumb = self.thumbnailize(img, int(bg_height / 2), crop=crop)
            cover_thumb_width = cover_thumb.size[0]
            cover_thumb_height = cover_thumb.size[1]
            covers_thumb.append({
                'cover': cover_thumb,
                'width': cover_thumb_width,
                'height': cover_thumb_height
                })
        #For having 4 covers for the mosaic
        if len(covers_thumb) == 2:
            covers_thumb.append(covers_thumb[1].copy())
            covers_thumb.append(covers_thumb[0].copy())
        elif len(covers_thumb) == 3:
            covers_thumb.append(covers_thumb[0].copy())
        #Covers position on background
        delta = bg_width - bg_height #The left border of album
        covers_thumb[0]['x'] = int(1*(bg_width - delta)/4 - covers_thumb[0]['width']/2 + delta)
        covers_thumb[0]['y'] = int(1*bg_height/4 - covers_thumb[0]['height']/2)
        covers_thumb[1]['x'] = int(3*(bg_width - delta)/4 - covers_thumb[1]['width']/2 + delta)
        covers_thumb[1]['y'] = int(1*bg_height/4 - covers_thumb[1]['height']/2)
        covers_thumb[2]['x'] = int(1*(bg_width - delta)/4 - covers_thumb[2]['width']/2 + delta)
        covers_thumb[2]['y'] = int(3*bg_height/4 - covers_thumb[2]['height']/2)
        covers_thumb[3]['x'] = int(3*(bg_width - delta)/4 - covers_thumb[3]['width']/2 + delta)
        covers_thumb[3]['y'] = int(3*bg_height/4 - covers_thumb[3]['height']/2)
        #Paste covers on background
        for i in range(0, 4):
            bg.paste(covers_thumb[i]['cover'],
                    (covers_thumb[i]['x'], covers_thumb[i]['y']),
                    covers_thumb[i]['cover']
                    )
        #Forground picture
        fg = Image.open(fg_picture).convert("RGBA")
        #Paste forground on background+cover
        bg.paste(fg, (0, 0), fg)
        self.thumb = bg

    def pictures_thumbnail(self, bg_picture, fg_picture, max_pictures=3):
        """ Makes thumbnails for picture folders.

        Arguments:
          * bg_picture -- the background picture
          * fg_picture -- the foreground picture

        Keyword argument:
          * max_pictures -- the maximum number of pictures on the thumbnail
        """
        #Background
        bg = Image.open(bg_picture).convert("RGBA")
        bg_width = bg.size[0]
        bg_height = bg.size[1]
        picts = []
        number_of_pictures = 0
        #One picture
        if len(self.img) == 1 or max_pictures == 1 and len(self.img) > 0:
            number_of_pictures = 1
            thumb = self.thumbnailize(
                    self.img[0],
                    bg_width - 20,
                    bg_height - 20,
                    crop=False
                    )
            x = int((bg_width - thumb.size[0]) / 2)
            y = int((bg_height - thumb.size[1]) / 2)
            picts.append({
                    'thumb': thumb,
                    'x': x,
                    'y': y
                    })
        #Two pictures
        elif len(self.img) == 2 or max_pictures == 2 and len(self.img) > 0:
            number_of_pictures = 2
            #Thumb 0
            thumb = self.thumbnailize(
                    self.img[0],
                    bg_width - 20,
                    int(0.53*bg_height),
                    crop=False
                    )
            picts.append({
                    'thumb': thumb,
                    'x': 10,
                    'y': 5
                    })
            #Thumb 1
            thumb = self.thumbnailize(
                    self.img[1],
                    bg_width - 20,
                    int(0.53*bg_height),
                    crop=False
                    )
            x = bg_width - thumb.size[0] - 10
            y = bg_height - thumb.size[1] - 5
            picts.append({
                    'thumb': thumb,
                    'x': x,
                    'y': y
                    })
        #Three pictures
        elif len(self.img) == 3 or max_pictures == 3 and len(self.img) > 0:
            number_of_pictures = 3
            #Thumb 0
            thumb = self.thumbnailize(self.img[0], 49, 56, crop=False)
            picts.append({
                    'thumb': thumb,
                    'x': 20,
                    'y': 5
                    })
            #Thumb 1
            thumb = self.thumbnailize(self.img[1], 49, 56, crop=False)
            x = int(bg_width - thumb.size[0] - 5)
            picts.append({
                    'thumb': thumb,
                    'x': x,
                    'y': 5
                    })
            #Thumb 2
            h = int(bg_height - max(picts[0]['thumb'].size[1], picts[1]['thumb'].size[1]) - 15)
            thumb = self.thumbnailize(self.img[2], 103, h, crop=False)
            x = int((bg_width - 15 - thumb.size[0])/2 + 15)
            y = int(bg_height - thumb.size[1] - 5)
            picts.append({
                    'thumb': thumb,
                    'x': x,
                    'y': y
                    })
        #Four pictures
        elif len(self.img) == 4 or max_pictures == 4 and len(self.img) > 0:
            number_of_pictures = 4
            #Thumb 0
            thumb = self.thumbnailize(
                    self.img[0],
                    int(bg_width/2 - 7.5),
                    int(bg_height/2 - 7.5),
                    crop=False
                    )
            x = int(1*bg_width/4 - thumb.size[0]/2)
            y = int(1*bg_height/4 - thumb.size[1]/2)
            picts.append({
                    'thumb': thumb,
                    'x': x,
                    'y': y
                    })
            #Thumb 1
            thumb = self.thumbnailize(
                    self.img[1],
                    int(bg_width/2 - 7.5),
                    int(bg_height/2 - 7.5),
                    crop=False
                    )
            x = int(3*bg_width/4 - thumb.size[0]/2)
            y = int(1*bg_height/4 - thumb.size[1]/2)
            picts.append({
                    'thumb': thumb,
                    'x': x,
                    'y': y
                    })
            #Thumb 2
            thumb = self.thumbnailize(
                    self.img[2],
                    int(bg_width/2 - 7.5),
                    int(bg_height/2 - 7.5),
                    crop=False
                    )
            x = int(1*bg_width/4 - thumb.size[0]/2)
            y = int(3*bg_height/4 - thumb.size[1]/2)
            picts.append({
                    'thumb': thumb,
                    'x': x,
                    'y': y
                    })
            #Thumb 3
            thumb = self.thumbnailize(
                    self.img[3],
                    int(bg_width/2 - 7.5),
                    int(bg_height/2 - 7.5),
                    crop=False
                    )
            x = int(3*bg_width/4 - thumb.size[0]/2)
            y = int(3*bg_height/4 - thumb.size[1]/2)
            picts.append({
                    'thumb': thumb,
                    'x': x,
                    'y': y
                    })

        #Paste pictures on background
        for i in range(0, number_of_pictures):
            bg.paste(
                    picts[i]['thumb'],
                    (picts[i]['x'], picts[i]['y']),
                    picts[i]['thumb']
                    )
        #Paste forground on background+pictures
        fg = Image.open(fg_picture).convert("RGBA")
        bg.paste(fg, (0, 0), fg)
        self.thumb = bg

    def other_thumbnail(self, fg_picture):
        """ Makes thumbnails for "other" folders

        Argument:
          * fg_picture -- the foreground picture to add
        """
        fg = Image.open(fg_picture).convert("RGBA")
        size = fg.size[0]
        if len(self.img) == 1:
            image = self.thumbnailize(self.img[0], size, crop=True)
            if image.size[0] == size and image.size[1] == size:
                image.paste(fg, (0, 0), fg)
                self.thumb = image

    def save_thumb(self, output_path, output_format='PNG'):
        """ Save the thumbnail in a file.

        Argument:
          * output_path -- the output path for the thumbnail
        Keyword argument:
          * format -- the format of the picture (PNG, JPEG,...)

        NOTE : The output format must be a PNG for a standard
               freedesktop thumbnail
        """
        if self.thumb is not None:
            self.thumb.save(output_path, output_format)
        else:
            print("E: [%s:Thumb.save_thumb] No thumbnail created" % __file__)


def search_pictures(path):
    """ Search for pictures in the folder

    Search for pictures in the folder and return their name as a list (or an
    empty list if no pictures were found).

    Argument:
      * path -- the path of the folder
    """
    files = os.listdir(path)
    pictures = []

    for f in files:
        _, ext = os.path.splitext(f)
        if ext in PICTURES_EXT:
            pictures.append(os.path.join(path, f))

        if len(pictures) >= 4:
            break

    return pictures


def search_pictures_recursiv(path):
    """ Search recursively for pictures in the folder

    Search for pictures in the subfolders and return their name as a list
    (or an empty list if no pictures were found).

    Argument:
      * path -- the path of the folder
    """
    pictures = []
    for root, dirs, files in os.walk(path):
        if len(pictures) <= 4:
            for file_ in files:
                if file_[-4:] in PICTURES_EXT:
                    pictures.append(os.path.join(path, root, file_))
                    break
        else:
            break
    return pictures


def match_path(path, path_list):
    """ Test if a folder is a sub-folder of another one in the list.

    Arguments
      * path -- path to check
      * path_list -- list of path
    """
    match = False
    #We add a slash at the end.
    if path[-1:] != "/":
        path += "/"
    for entry in path_list:
        #We add a slash at the end.
        if entry[-1:] != "/":
            entry += "/"
        if re.match(r"^" + entry + ".*", path):
            if path != entry:
                match = True
                break
    return match


def gvfs_uri_to_path(uri):
    """Returns local file path from gvfs URI

    Arguments:
    uri -- the gvfs URI
    """
    if not re.match(r"^[a-zA-Z0-9_-]+://", uri):
        return uri

    gvfs = Gio.Vfs.get_default()
    return gvfs.get_file_for_uri(uri).get_path()


def has_more_music(root: str) -> bool:
    music = 0
    pictures = 0
    
    for _, _, files in os.walk(root):
        for f in files:
            _, ext = os.path.splitext(f)

            if ext in MUSIC_EXT:
                music += 1
            elif ext in PICTURES_EXT:
                pictures += 1

    return music > pictures

if __name__ == "__main__":
    if len(sys.argv) < 2 or len(sys.argv) > 3:
        print("Cover thumbnailer - %s" % __doc__)
        print("Version: %s" % __version__)
        print(__copyright__)
        sys.exit(1)

    input_folder = gvfs_uri_to_path(sys.argv[1])

    if len(sys.argv) == 3:
        output_file = gvfs_uri_to_path(sys.argv[2])

    elif len(sys.argv) == 2:
        output_file = "./out.png"

    #If input path does not exists
    if not os.path.isdir(input_folder):
        print("E: [%s:__main__] '%s' is not a directory" % (__file__, input_folder))
        sys.exit(2)

    # Determine the type of folder we get. Is it music folder, pictures?
    is_music_folder = has_more_music(input_folder)

    # Music folders
    if is_music_folder:
        covers = search_pictures(input_folder)

        if len(covers) == 0:
            covers = search_pictures_recursiv(input_folder)
                
        elif len(covers) > 0:
            thumbnail = Thumb(covers)
            thumbnail.music_thumbnail(MUSIC_BG, MUSIC_FG)
            thumbnail.save_thumb(output_file, "PNG")
            
    else:
        # Picture folders
        picture_list = search_pictures(input_folder)

        if len(picture_list) == 0:
            picture_list = search_pictures_recursiv(input_folder)

        thumbnail = Thumb(picture_list)
        thumbnail.pictures_thumbnail(PICTURES_BG, PICTURES_FG)
        thumbnail.save_thumb(output_file, "PNG")
